const schemaTestata = {
    
    numero: { 
      label: 'Numero: ', 
      type: 'numero', 
      obbligatorio:false, 
      visibile:true ,
      campoElenco:'',
      campoNome:'',
      layout: { 
        web: { 
          visibile:true,
          margineSn: 1 ,
          margineDx: 4 ,
          height:30, 
          width:10,
          bordoColor:'grey', 
          bordoWidth:1,
          labelColor:'',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        },
        
        mobile: { 
          visibile:true,
          margineSn: 2,
          margineDx: 5 ,
          height:40, 
          width:20,
          bordoColor:'', 
          bordoWidth:1,
          labelColor:'blue',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        } 
        }
      },
      dataOrdine: { 
        label: 'DataOrdine', 
        type: 'data', 
        obbligatorio:true, 
        visibile:true , 
        campoElenco:'',
        campoNome:'',
        layout: { 
        web: { 
          visibile:true,
          margineSn: 1 ,
          margineDx: 4 ,
          height:30, 
          width:15,
          bordoColor:'grey', 
          bordoWidth:1,
          labelColor:'',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        },
        
        mobile: { 
          visibile:true,
          margineSn: 2,
          margineDx: 5 ,
          height:40, 
          width:20,
          bordoColor:'', 
          bordoWidth:1,
          labelColor:'blue',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        }  
      }
        },
        dataEvasione: { 
          label: 'Data Evasione', 
          type: 'data', 
          obbligatorio:true, 
          visibile:true , 
          campoElenco:'',
          campoNome:'',
          layout: { 
         web: { 
          visibile:true,
          margineSn: 1 ,
          margineDx: 4 ,
          height:30, 
          width:15,
          bordoColor:'grey', 
          bordoWidth:1,
          labelColor:'',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        },
        
        mobile: { 
          visibile:true,
          margineSn: 2,
          margineDx: 5 ,
          height:40, 
          width:20,
          bordoColor:'', 
          bordoWidth:1,
          labelColor:'blue',
          inputColor:'',     
          row: 1, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        }   
      },
    },
     evasioneParziale: { 
        label: 'EV', 
        type: 'text', 
        obbligatorio:false, 
        visibile:true , 
        campoElenco:'',
        campoNome:'',
        layout: { 
          web: { 
           visibile:true,
           margineSn: 1 ,
           margineDx: 4 ,
           height:30, 
           width:8,
           bordoColor:'grey', 
           bordoWidth:1,
           labelColor:'',
           inputColor:'',     
           row: 1, 
           pagina:1,
           tipoElenco:'',
           campo:'',
           tipoInput:''
         },
         
         mobile: { 
           visibile:true,
           margineSn: 2,
           margineDx: 5 ,
           height:40, 
           width:20,
           bordoColor:'', 
           bordoWidth:1,
           labelColor:'blue',
           inputColor:'',     
           row: 1, 
           pagina:1,
           tipoElenco:'',
           campo:'',
           tipoInput:''
         }   
        },
      },
    codice: { 
        label: 'Cod/Cliente', 
        type: 'text', 
        obbligatorio:true,
        visibile:true , 
        campoElenco:'',
        campoNome:'',
      layout: { 
        web: { 
          visibile:true,
          margineSn: 1 ,
          margineDx: 4 ,
          height:30, 
          width:15,
          bordoColor:'grey', 
          bordoWidth:1,
          labelColor:'',
          inputColor:'',     
          row: 2, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        },
        mobile: { 
           visibile:true,
           margineSn: 2,
           margineDx: 5 ,
           height:40, 
           width:20,
           bordoColor:'', 
           bordoWidth:1,
           labelColor:'blue',
           inputColor:'',     
           row: 1, 
           pagina:1,
           tipoElenco:'',
           campo:'',
           tipoInput:''
         }   
         },
      },
      nome: { 
        label: 'Cliente', 
        type: 'text', 
        obbligatorio:true,
        visibile:true , 
        campoElenco:'',
        campoNome:'',
      layout: { 
        web: { 
          visibile:true,
          margineSn: 1 ,
          margineDx: 4 ,
          height:30, 
          width:70,
          bordoColor:'grey', 
          bordoWidth:1,
          labelColor:'',
          inputColor:'',     
          row: 2, 
          pagina:1,
          tipoElenco:'',
          campo:'',
          tipoInput:''
        },
        mobile: { 
           visibile:true,
           margineSn: 2,
           margineDx: 5 ,
           height:40, 
           width:20,
           bordoColor:'', 
           bordoWidth:1,
           labelColor:'blue',
           inputColor:'',     
           row: 1, 
           pagina:1,
           tipoElenco:'',
           campo:'',
           tipoInput:''
         }   
         },
      },
      totaleOrdine: { 
        label: 'totale', 
        type: 'text', 
        obbligatorio:false,
        visibile:true , 
        campoElenco:'',
        campoNome:'',
        layout: { 
          web: { 
            visibile:true,
            margineSn: 1 ,
            margineDx: 4 ,
            height:30, 
            width:20,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          },
          mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          }    }
        },
        ivaOrdine: { 
          label: 'iva', 
          type: 'text', 
          obbligatorio:false,
          visibile:true , 
          campoElenco:'',
        campoNome:'',
          layout: { 
            web: { 
              visibile:true,
              margineSn: 1 ,
              margineDx: 4 ,
              height:30, 
              width:20,
              bordoColor:'grey', 
              bordoWidth:1,
              labelColor:'',
              inputColor:'',     
              row: 3, 
              pagina:1,
              tipoElenco:'',
              campo:'',
              tipoInput:''
            },
            mobile: { 
              visibile:true,
              margineSn: 2,
              margineDx: 5 ,
              height:40, 
              width:20,
              bordoColor:'', 
              bordoWidth:1,
              labelColor:'blue',
              inputColor:'',     
              row: 1, 
              pagina:1,
              tipoElenco:'',
              campo:'',
              tipoInput:''
            }  
           }
          },
     
  };

const schemaRighe= {
 codice: { 
  label: 'codice:', 
  type: 'text', 
  obbligatorio:false,
  visibile:true , 
  campoElenco:'',
  campoNome:'',
  layout: { 
    web: { 
      visibile:true,
      margineSn: 1 ,
      margineDx: 2 ,
      height:30, 
      width:15,
      bordoColor:'grey', 
      bordoWidth:1,
      labelColor:'',
      inputColor:'',     
      row: 1, 
      pagina:1,
      tipoElenco:'',
      campo:'',
      tipoInput:''
    },
    mobile: { 
      visibile:true,
      margineSn: 2,
      margineDx: 5 ,
      height:40, 
      width:20,
      bordoColor:'', 
      bordoWidth:1,
      labelColor:'blue',
      inputColor:'',     
      row: 1, 
      pagina:1,
      tipoElenco:'',
      campo:'',
      tipoInput:''
    }  
   }
  }, 
prodotto: { 
  label: 'Prodotto: ', 
  type: 'text', 
  obbligatorio:false,
  visibile:true , 
  campoElenco:'',
  campoNome:'',
  layout: { 
    web: { 
      visibile:true,
      margineSn: 1 ,
      margineDx: 4 ,
      height:30, 
      width:70,
      bordoColor:'grey', 
      bordoWidth:1,
      labelColor:'',
      inputColor:'',     
      row: 1, 
      pagina:1,
      tipoElenco:'',
      campo:'',
      tipoInput:'', 
    },
      mobile: { 
        visibile:true,
        margineSn: 2,
        margineDx: 5 ,
        height:40, 
        width:20,
        bordoColor:'', 
        bordoWidth:1,
        labelColor:'blue',
        inputColor:'',     
        row: 1, 
        pagina:1,
        tipoElenco:'',
        campo:'',
        tipoInput:''
      }  
  },
},
  prezzoListino: { 
    label: 'Listino', 
    type: 'data', 
    obbligatorio:true, 
    visibile:true , 
    campoElenco:'',
    campoNome:'',
    layout: { 
     web: { 
      visibile:true,
      margineSn: 1 ,
      margineDx: 2 ,
      height:30, 
      width:20,
      bordoColor:'grey', 
      bordoWidth:1,
      labelColor:'',
      inputColor:'',     
      row: 2, 
      pagina:1,
      tipoElenco:'',
      campo:'',
      tipoInput:'', 
    },
    mobile: { 
      visibile:true,
      margineSn: 2,
      margineDx: 2,
      height:40, 
      width:20,
      bordoColor:'', 
      bordoWidth:1,
      labelColor:'blue',
      inputColor:'',     
      row: 1, 
      pagina:1,
      tipoElenco:'',
      campo:'',
      tipoInput:''
    } 
   } 
    },
   'sconto%': { 
    label: '%', 
    type: 'numero', 
    obbligatorio:true, 
    visibile:true ,
    campoElenco:'',
    campoNome:'',
        layout: { 
          web: { 
            visibile:true,
            margineSn: 1 ,
            margineDx: 2 ,
            height:30, 
            width:8,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 2, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          },
          mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 2 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
        } 
        },
      scontoImporto: { 
        label: 'Sconto', 
        type: 'data', 
        obbligatorio:true, 
        visibile:true ,
        campoElenco:'',
        campoNome:'',
        layout: { 
          web: { 
            visibile:true,
            margineSn: 1 ,
            margineDx: 2 ,
            height:30, 
            width:20,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 2, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          },
          mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
        } 
        },
        prezzoUnitario: { 
          label: 'Prezzo', 
          type: 'numero', 
          obbligatorio:true, 
          visibile:true ,
          campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 1 ,
            margineDx: 2 ,
            height:30, 
            width:20,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 2, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
          },
        
        quantita: { 
          label: 'QT', 
          type: 'numero', 
          obbligatorio:true, 
          visibile:true ,
          campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 1 ,
            margineDx: 2 ,
            height:30, 
            width:8,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
        },
        tipoQuantita: { 
          label: 'TP', 
          type: 'text', 
          obbligatorio:true, 
          visibile:true ,
          campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 0 ,
            margineDx: 2 ,
            height:30, 
            width:10,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx:2 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         }, 
        },
        prezzoTotale: { 
          label: 'Totale',
          type: 'numero', 
          obbligatorio:true, 
          visibile:true ,
          campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 0 ,
            margineDx: 2 ,
            height:30, 
            width:20,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
          },
      '%iva': { 
        label: '%iva', 
        type: 'numero', 
        obbligatorio:true, 
        visibile:true ,
        campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 0,
            margineDx: 2 ,
            height:30, 
            width:8,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
        },
        importoIva: { 
          label: 'iva', 
          type: 'numero',
           obbligatorio:true, 
           visibile:true ,
           campoElenco:'',
          campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 0 ,
            margineDx: 2 ,
            height:30, 
            width:15,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
          },
          norma: { 
            label: 'norma', 
            type: 'text', 
            obbligatorio:true, 
            visibile:true ,
            campoElenco:'',
            campoNome:'',
          layout: { 
            web: { 
            visibile:true,
            margineSn: 0 ,
            margineDx:0 ,
            height:30, 
            width:25,
            bordoColor:'grey', 
            bordoWidth:1,
            labelColor:'',
            inputColor:'',     
            row: 3, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:'', 
          }, 
            mobile: { 
            visibile:true,
            margineSn: 2,
            margineDx: 5 ,
            height:40, 
            width:20,
            bordoColor:'', 
            bordoWidth:1,
            labelColor:'blue',
            inputColor:'',     
            row: 1, 
            pagina:1,
            tipoElenco:'',
            campo:'',
            tipoInput:''
          } 
         },
            },
}

  export  {schemaTestata,schemaRighe}